#!/usr/bin/env python3
"""Merge a chapter-based LaTeX document into one file for LLM upload.

By default this expands active ``\\subfile``, ``\\input``, and ``\\include``
commands in ``main-detail.tex`` and writes ``main-detail-merged.tex``.
Subfile preambles and their ``document`` wrappers are removed while the root
document's preamble is preserved.

Usage:
    python3 merge_tex.py
    python3 merge_tex.py -o /tmp/konomeno-detail.tex
    python3 merge_tex.py --no-markers -o -
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path


DETAIL_DIR = Path(__file__).resolve().parent.parent  # detail/
DEFAULT_ROOT = DETAIL_DIR / "main-detail.tex"
DEFAULT_OUTPUT = DETAIL_DIR.parent / "local" / "build-artifacts" / "main-detail-merged.tex"

INCLUDE_RE = re.compile(
    r"^(?P<indent>\s*)\\(?P<command>subfile|input|include)\s*"
    r"\{(?P<target>[^{}]+)\}(?P<tail>\s*(?:%.*)?)$"
)
BEGIN_DOCUMENT_RE = re.compile(r"^[ \t]*\\begin\s*\{document\}[^\n]*(?:\n|$)", re.MULTILINE)
END_DOCUMENT_RE = re.compile(r"^[ \t]*\\end\s*\{document\}[^\n]*(?:\n|$)", re.MULTILINE)
DOCUMENT_CLASS_RE = re.compile(r"^[ \t]*\\documentclass(?:\[[^]]*\])?\s*\{", re.MULTILINE)


class MergeError(RuntimeError):
    """Raised when includes cannot be merged without guessing."""


class TexMerger:
    def __init__(self, project_root: Path, markers: bool = True):
        self.project_root = project_root.resolve()
        self.markers = markers
        self.inlined_files: list[Path] = []

    def merge(self, root_file: Path) -> str:
        root_file = root_file.resolve()
        self._require_inside_project(root_file)
        if not root_file.is_file():
            raise MergeError(f"Root TeX file not found: {root_file}")

        source = root_file.read_text(encoding="utf-8")
        expanded = self._expand(source, root_file, (root_file,))
        relative_root = root_file.relative_to(self.project_root).as_posix()
        header = (
            "% AUTO-GENERATED by merge_tex.py; do not edit this file directly.\n"
            f"% Root source: {relative_root}\n"
            "% Active \\subfile, \\input, and \\include commands are inlined recursively.\n\n"
        )
        return header + expanded.rstrip() + "\n"

    def _expand(self, source: str, including_file: Path, stack: tuple[Path, ...]) -> str:
        output: list[str] = []
        for line in source.splitlines(keepends=True):
            line_without_newline = line.rstrip("\r\n")
            match = INCLUDE_RE.fullmatch(line_without_newline)
            if not match:
                output.append(line)
                continue

            target = self._resolve_target(match.group("target"), including_file)
            if target in stack:
                chain = " -> ".join(path.name for path in (*stack, target))
                raise MergeError(f"Cyclic TeX include detected: {chain}")

            tail = match.group("tail").strip()
            if tail:
                output.append(f"{match.group('indent')}{tail}\n")
            output.append(self._inline(target, (*stack, target)))
        return "".join(output)

    def _inline(self, path: Path, stack: tuple[Path, ...]) -> str:
        source = path.read_text(encoding="utf-8")
        body = self._document_body(source, path)
        expanded = self._expand(body, path, stack).strip("\r\n")
        self.inlined_files.append(path)
        if not self.markers:
            return expanded + "\n"

        relative_path = path.relative_to(self.project_root).as_posix()
        return (
            f"\n% ===== BEGIN INLINED FILE: {relative_path} =====\n"
            f"{expanded}\n"
            f"% ===== END INLINED FILE: {relative_path} =====\n"
        )

    def _document_body(self, source: str, path: Path) -> str:
        begin = BEGIN_DOCUMENT_RE.search(source)
        ends = list(END_DOCUMENT_RE.finditer(source))
        if begin and ends and ends[-1].start() >= begin.end():
            return source[begin.end():ends[-1].start()]
        if begin or ends or DOCUMENT_CLASS_RE.search(source):
            relative_path = path.relative_to(self.project_root).as_posix()
            raise MergeError(f"Incomplete document wrapper in included file: {relative_path}")
        return source

    def _resolve_target(self, raw_target: str, including_file: Path) -> Path:
        target = Path(raw_target.strip())
        if target.suffix == "":
            target = target.with_suffix(".tex")

        candidates = []
        if target.is_absolute():
            candidates.append(target.resolve())
        else:
            candidates.extend([
                (including_file.parent / target).resolve(),
                (self.project_root / target).resolve(),
            ])

        for candidate in dict.fromkeys(candidates):
            if candidate.is_file():
                self._require_inside_project(candidate)
                return candidate

        relative_source = including_file.relative_to(self.project_root).as_posix()
        raise MergeError(f"Included TeX file not found from {relative_source}: {raw_target}")

    def _require_inside_project(self, path: Path) -> None:
        try:
            path.relative_to(self.project_root)
        except ValueError as error:
            raise MergeError(f"Refusing to inline a file outside {self.project_root}: {path}") from error


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.chmod(0o644)
    os.replace(temporary_path, path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="章ごとのTeXを、ブラウザ版LLMへ渡しやすい単一TeXへ展開します。",
    )
    parser.add_argument(
        "root",
        nargs="?",
        type=Path,
        default=DEFAULT_ROOT,
        help="ルートTeX（既定: main-detail.tex）",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="出力先。- なら標準出力（既定: main-detail-merged.tex）",
    )
    parser.add_argument(
        "--no-markers",
        action="store_true",
        help="インライン化したファイルの境界コメントを付けない",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root if args.root.is_absolute() else (Path.cwd() / args.root)
    merger = TexMerger(DETAIL_DIR, markers=not args.no_markers)
    try:
        merged = merger.merge(root)
        if args.output == "-":
            sys.stdout.write(merged)
            destination = "stdout"
        else:
            output = Path(args.output)
            if not output.is_absolute():
                output = Path.cwd() / output
            output = output.resolve()
            if output == root.resolve():
                raise MergeError("Output path must not overwrite the root TeX file")
            atomic_write(output, merged)
            destination = str(output)
    except (MergeError, OSError, UnicodeError) as error:
        print(f"merge_tex.py: error: {error}", file=sys.stderr)
        return 1

    print(
        f"Merged {len(merger.inlined_files)} TeX files into {destination}",
        file=sys.stderr if args.output == "-" else sys.stdout,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
